# fly.toml file generated for fly-log-shipper-logtail on 2022-03-11T16:41:44+11:00

app = "fly-log-shipper-logtail"


[metrics]
  path = "/metrics"
  port = 9598
  
[[services]]
  http_checks = []
  internal_port = 8686