[transforms.remap_logflare_loglevel]
  type = "remap"
  inputs = ["log_json"]
  source = '''
    .level = .log.level
  '''

[sinks.logflare]
  type = "http"
  inputs = ["remap_logflare_loglevel"]
  uri = "https://api.logflare.app/logs/vector?source=${LOGFLARE_SOURCE_TOKEN}"
  request.headers = {"X-API-Key" = "${LOGFLARE_API_KEY}"}
  encoding.codec = "json"
  compression = "none"

